#!/usr/bin/env php
<?php

declare(strict_types=1);

use DBrekelmans\BrowserDriverInstaller\Archive\MultiExtractor;
use DBrekelmans\BrowserDriverInstaller\Archive\TarGzExtractor;
use DBrekelmans\BrowserDriverInstaller\Archive\ZipExtractor;
use DBrekelmans\BrowserDriverInstaller\Browser;
use DBrekelmans\BrowserDriverInstaller\Browser\Chromium;
use DBrekelmans\BrowserDriverInstaller\Browser\Firefox;
use DBrekelmans\BrowserDriverInstaller\Browser\GoogleChrome;
use DBrekelmans\BrowserDriverInstaller\Browser\MsEdge;
use DBrekelmans\BrowserDriverInstaller\Command\DetectCommand;
use DBrekelmans\BrowserDriverInstaller\CommandLine\ShellCommandLineEnvironment;
use DBrekelmans\BrowserDriverInstaller\Driver;
use DBrekelmans\BrowserDriverInstaller\Driver\ChromeDriver;
use DBrekelmans\BrowserDriverInstaller\Driver\GeckoDriver;
use DBrekelmans\BrowserDriverInstaller\Driver\MsEdgeDriver;
use Symfony\Component\Console\Application;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpClient\NativeHttpClient;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$httpClient = new NativeHttpClient();
$filesystem = new Filesystem();
$zipArchive = new ZipArchive();
$shellCommandLineEnv = new ShellCommandLineEnvironment();
$tarGzExtractor = new TarGzExtractor();
$zipExtractor = new ZipExtractor($zipArchive);
$multiExtractor = new MultiExtractor();
$multiExtractor->register($zipExtractor);
$multiExtractor->register($tarGzExtractor);

$browserPathResolverFactory = new Browser\PathResolverFactory();
$browserPathResolverFactory->register(new GoogleChrome\PathResolver());
$browserPathResolverFactory->register(new Chromium\PathResolver());
$browserPathResolverFactory->register(new Firefox\PathResolver());
$browserPathResolverFactory->register(new MsEdge\PathResolver());

$browserVersionResolverFactory = new Browser\VersionResolverFactory();
$browserVersionResolverFactory->register(new GoogleChrome\VersionResolver($shellCommandLineEnv));
$browserVersionResolverFactory->register(new Chromium\VersionResolver($shellCommandLineEnv));
$browserVersionResolverFactory->register(new Firefox\VersionResolver($shellCommandLineEnv));
$browserVersionResolverFactory->register(new MsEdge\VersionResolver($shellCommandLineEnv));

$driverVersionResolverFactory = new Driver\VersionResolverFactory();
$driverVersionResolverFactory->register($chromeDriverVersionResolver = new ChromeDriver\VersionResolver($httpClient));
$driverVersionResolverFactory->register($geckoDriverVersionResolver = new GeckoDriver\VersionResolver($httpClient));
$driverVersionResolverFactory->register($msedgeDriverVersionResolver = new MsEdgeDriver\VersionResolver($httpClient));

$driverDownloaderFactory = new Driver\DownloaderFactory();
$driverDownloaderFactory->register(new ChromeDriver\Downloader($filesystem, $httpClient, $multiExtractor, $chromeDriverDownloadUrlResolver = new ChromeDriver\DownloadUrlResolver($httpClient)));
$driverDownloaderFactory->register(new GeckoDriver\Downloader($filesystem, $httpClient, $multiExtractor));
$driverDownloaderFactory->register(new MsEdgeDriver\Downloader($filesystem, $httpClient, $multiExtractor, $msedgeDriverDownloadUrlResolver = new MsEdgeDriver\DownloadUrlResolver()));

$browserFactory = new Browser\BrowserFactory($browserPathResolverFactory, $browserVersionResolverFactory);
$driverFactory = new Driver\DriverFactory($driverVersionResolverFactory);

$application->add(new DetectCommand());
$application->add(new GoogleChrome\Command($filesystem, $browserFactory, $driverFactory, $driverDownloaderFactory));
$application->add(new Chromium\Command($filesystem, $browserFactory, $driverFactory, $driverDownloaderFactory));
$application->add(new Firefox\Command($filesystem, $browserFactory, $driverFactory, $driverDownloaderFactory));
$application->add(new ChromeDriver\Command($chromeDriverVersionResolver, $driverDownloaderFactory));
$application->add(new GeckoDriver\Command($geckoDriverVersionResolver, $driverDownloaderFactory));
$application->add(new MsEdge\Command($filesystem, $browserFactory, $driverFactory, $driverDownloaderFactory));

$application->setDefaultCommand(DetectCommand::NAME);

$application->run();
