#!/usr/bin/env php
<?php

declare(strict_types=1);

use DBrekelmans\BrowserDriverInstaller\Browser;
use DBrekelmans\BrowserDriverInstaller\Browser\GoogleChrome;
use DBrekelmans\BrowserDriverInstaller\Command\DriverCommand;
use DBrekelmans\BrowserDriverInstaller\Driver;
use DBrekelmans\BrowserDriverInstaller\Driver\ChromeDriver;
use Symfony\Component\Console\Application;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpClient\NativeHttpClient;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$httpClient = new NativeHttpClient();
$filesystem = new Filesystem();
$zipArchive = new ZipArchive();

$browserPathResolverFactory = new Browser\PathResolverFactory();
$browserPathResolverFactory->register(new GoogleChrome\PathResolver());

$browserVersionResolverFactory = new Browser\VersionResolverFactory();
$browserVersionResolverFactory->register(new GoogleChrome\VersionResolver());

$driverVersionResolverFactory = new Driver\VersionResolverFactory();
$driverVersionResolverFactory->register(new ChromeDriver\VersionResolver($httpClient));

$driverDownloaderFactory = new Driver\DownloaderFactory();
$driverDownloaderFactory->register(new ChromeDriver\Downloader($filesystem, $httpClient, $zipArchive));

$browserFactory = new Browser\BrowserFactory($browserPathResolverFactory, $browserVersionResolverFactory);
$driverFactory = new Driver\DriverFactory($driverVersionResolverFactory);

$application->add(
    new DriverCommand(
        $filesystem,
        $browserFactory,
        $driverFactory,
        $driverDownloaderFactory
    )
);

// TODO: Split commands into browser:google-chrome, browser:chromium, browser:firefox, driver:chrome, driver:gecko

$application->setDefaultCommand('driver');
$application->run();
