name: Add PHAR Distribution

on:
  push:
    branches:
      - master
      - gpg-sign-phar
    paths-ignore:
      - ".dist/**"

jobs:
  phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: zip
          coverage: none
          tools: phive
      - id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer install --no-interaction --no-dev --optimize-autoloader
      - run: phive install --force-accept-unsigned
      - run: .phive/tools/box compile
      - name: Configure GPG signing key
        run: echo "$GPG_SIGNING_KEY" | gpg --import --no-tty --batch --yes
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Sign PHAR
        run: gpg -u "$GPG_ID" --detach-sign --output .dist/bdi.phar.asc .dist/bdi.phar
        env:
          GPG_ID: ${{ secrets.GPG_ID }}
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: Daniël Brekelmans
          author_email: dbrekelmans@users.noreply.github.com
          message: "Update PHAR distribution"
          add: ".dist/*"
