name: Quality Assurance

on:
  pull_request

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: zip
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/phpunit
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: zip
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/phpstan analyse --error-format=github
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: zip
          coverage: none
      - uses: ramsey/composer-install@v1
      - run: vendor/bin/phpcs --warning-severity=0
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [7.4, 8.0, 8.1, 8.2]
        dependencies: [locked]
        include:
          - os: ubuntu-latest
            php: 7.4
            dependencies: lowest
          - os: ubuntu-latest
            php: 8.0
            dependencies: lowest
          - os: ubuntu-latest
            php: 8.1
            dependencies: lowest
          - os: ubuntu-latest
            php: 8.2
            dependencies: lowest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: none
      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--no-dev --optimize-autoloader --prefer-dist"
      - run: php bdi
      - run: php bdi detect
      - run: php bdi browser:google-chrome -vvv
      - run: php bdi browser:firefox -vvv
      - run: php bdi driver:chromedriver -vvv
      - run: php bdi driver:geckodriver -vvv
